services:
  loki:
    build:
      context: ./loki
      dockerfile: Dockerfile
    container_name: loki
    healthcheck:
      test: [ "CMD", "/usr/bin/loki", "-version" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - "3100:3100"
    networks:
      - main-network

  prometheus:
    build: 
      context: ./prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9090:9090"
    volumes:
      - prometheus-storage:/prometheus
    networks:
      - main-network

  grafana:
    build: 
      context: ./grafana
      dockerfile: Dockerfile
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
      - loki
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - main-network

  promtail:
    build:
      context: ./promtail
      dockerfile: Dockerfile
    container_name: promtail
    restart: unless-stopped
    depends_on:
      - loki
    command: ["-config.file=/etc/promtail/config.yml"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "9080:9080"
    networks:
      - main-network

networks:
  main-network:
    external: true

volumes:
  prometheus-storage:
  grafana-storage: